-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    "idTelegram" character(200) NOT NULL,
    "Username" character(200),
    "Telephone" character(200),
    "Name" character(200),
    "LastName" character(200),
    PRIMARY KEY ("idTelegram")
);

CREATE TABLE IF NOT EXISTS public."UsersAccepted"
(
    "IDTelegram" character(200) NOT NULL,
    "Username" character(200),
    "Accepted" boolean,
    PRIMARY KEY ("IDTelegram")
);

CREATE TABLE IF NOT EXISTS public."UsersBan"
(
    "IDTelegram" character(200) NOT NULL,
    "Username" character(200),
    "Bans" boolean,
    PRIMARY KEY ("IDTelegram")
);

CREATE TABLE IF NOT EXISTS public."UniqueNum"
(
    "UniqueNum" character(200),
    "Used" boolean
);
END;