-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 23:02:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `LastName` VARCHAR(100) NULL,
  `IDTelegram` VARCHAR(150) NULL,
  `Telephone` VARCHAR(100) NULL,
  `Username` VARCHAR(100) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`UsersAccepted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UsersAccepted` (
  `idUsersAccepted` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NULL,
  `IDTelegram` VARCHAR(100) NULL,
  `Accepted` TINYINT NULL,
  PRIMARY KEY (`idUsersAccepted`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`UsersBans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UsersBans` (
  `idUsersBans` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NULL,
  `IDTelegram` VARCHAR(100) NULL,
  `UsersBans` TINYINT NULL,
  PRIMARY KEY (`idUsersBans`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`UniqueNum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UniqueNum` (
  `idUniqueNum` INT NOT NULL AUTO_INCREMENT,
  `UniqueNum` VARCHAR(200) NULL,
  `Used` TINYINT NULL,
  PRIMARY KEY (`idUniqueNum`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
